version: "3"

networks:
  loki:

services:
  loki:
    image: grafana/loki:2.2.1
    ports:
      - "9091:3100"
    volumes:
      - /home/dev/repository/loki:/etc/loki
    command: -config.file=/etc/loki/loki-config.yaml
    networks:
      - loki

  promtail:
    image: grafana/promtail:2.2.1
    volumes:
      - /var/log:/var/log
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /home/dev/repository/loki:/etc/promtail 
    command: -config.file=/etc/promtail/promtail-config.yaml
    networks:
      - loki
